export const getDps = [
  { tribe: "Abayon", link: "https://getdp.co/pkd" },
  { tribe: "Fulani", link: "https://getdp.co/Xyi" },
  { tribe: "Hausa", link: "https://getdp.co/XyV" },
  { tribe: "Yoruba", link: "https://getdp.co/Xyq" },
  { tribe: "Igbo", link: "https://getdp.co/Xyo" },
  { tribe: "Ibibio", link: "https://getdp.co/Xyj" },
  { tribe: "Ijaw", link: "https://getdp.co/XyX" },
  { tribe: "kanuri", link: "https://getdp.co/Xyp" },
  { tribe: "Tiv", link: "https://getdp.co/XyL" },
  { tribe: "Nupe", link: "https://getdp.co/XCR" },
  { tribe: "Efik", link: "https://getdp.co/XD0" },
  { tribe: "Annang", link: "https://getdp.co/XDa" },
  { tribe: "Igala", link: "https://getdp.co/XDu" },
  { tribe: "Gwari", link: "https://getdp.co/XD1" },
  { tribe: "Jakun", link: "https://getdp.co/XDS" },
  { tribe: "Edo", link: "https://getdp.co/XDM" },
  { tribe: "Abua", link: "https://getdp.co/pkK" },
  { tribe: "Achipa", link: "https://getdp.co/pkP" },
  { tribe: "Adim", link: "https://getdp.co/pki" },
  { tribe: "Adun", link: "https://getdp.co/pkV" },
  { tribe: "Affade", link: "https://getdp.co/pkj" },
  { tribe: "Afizere", link: "https://getdp.co/pko" },
  { tribe: "Afo", link: "https://getdp.co/pkX" },
  { tribe: "Agbo", link: "https://getdp.co/pkp" },
  { tribe: "Akaju-Ndem", link: "https://getdp.co/pkL" },
  { tribe: "Akweya-yachi", link: "https://getdp.co/pkN" },
  { tribe: "Alago", link: "https://getdp.co/pkr" },
  { tribe: "Amo", link: "https://getdp.co/pks" },
  { tribe: "Anaguta", link: "https://getdp.co/pkt" },
  { tribe: "Andoni", link: "https://getdp.co/pkv" },
  { tribe: "Angas", link: "https://getdp.co/pkw" },
  { tribe: "Ankwei", link: "https://getdp.co/pkE" },
  { tribe: "Anyima", link: "https://getdp.co/pkZ" },
  { tribe: "Attakar", link: "https://getdp.co/pkF" },
  { tribe: "Auyoka", link: "https://getdp.co/pky" },
  { tribe: "Awori", link: "https://getdp.co/pkz" },
  { tribe: "Ayu", link: "https://getdp.co/pkB" },
  //   { tribe: "Bachama", link: "" },
  //   { tribe: "Bachere", link: "" },
  //   { tribe: "Bada", link: "" },
  //   { tribe: "Bade", link: "" },
  //   { tribe: "Bahumono", link: "" },
  //   { tribe: "Bakulung", link: "" },
  //   { tribe: "Bali", link: "" },
  //   { tribe: "Bambora", link: "" },
  //   { tribe: "Babur", link: "" },
  //   { tribe: "baruba", link: "" },
  //   { tribe: "Bamkubo", link: "" },
  //   { tribe: "Banda", link: "" },
  //   { tribe: "Banka", link: "" },
  //   { tribe: "Banso", link: "" },
  //   { tribe: "Bara", link: "" },
  //   { tribe: "Barke", link: "" },
  //   { tribe: "Bashiri", link: "" },
  //   { tribe: "Bassa", link: "" },
  //   { tribe: "Batta", link: "" },
  //   { tribe: "Baushi", link: "" },
  //   { tribe: "Baya", link: "" },
  //   { tribe: "Bekwarra", link: "" },
  //   { tribe: "Bele", link: "" },
  //   { tribe: "Betso", link: "" },
  //   { tribe: "Bette", link: "" },
  //   { tribe: "Bilei", link: "" },
  //   { tribe: "Bille", link: "" },
  //   { tribe: "Bina", link: "" },
  //   { tribe: "Bini (Edo)", link: "" },
  //   { tribe: "Birom", link: "" },
  //   { tribe: "Bkkos", link: "" },
  //   { tribe: "Bobua", link: "" },
  //   { tribe: "Boki(Nki)", link: "" },
  //   { tribe: "Boko", link: "" },
  //   { tribe: "Bole(Bolewa)", link: "" },
  //   { tribe: "Boma", link: "" },
  //   { tribe: "Bomboro", link: "" },
  //   { tribe: "Botlere", link: "" },
  //   { tribe: "Buduma", link: "" },
  //   { tribe: "Buji", link: "" },
  //   { tribe: "Buli", link: "" },
  //   { tribe: "Bunu", link: "" },
  //   { tribe: "Bura", link: "" },
  //   { tribe: "Burak", link: "" },
  //   { tribe: "Burma", link: "" },
  //   { tribe: "Buru", link: "" },
  //   { tribe: "Bwall", link: "" },
  //   { tribe: "Bwatiye", link: "" },
  //   { tribe: "Bwazza", link: "" },
  //   { tribe: "challa", link: "" },
  //   { tribe: "duka", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
];
