export const getDps = [
  { tribe: "Fulani", link: "https://getdp.co/Xyi" },
  { tribe: "Hausa", link: "https://getdp.co/XyV" },
  { tribe: "Yoruba", link: "https://getdp.co/Xyq" },
  { tribe: "Igbo", link: "https://getdp.co/Xyo" },
  { tribe: "Ibibio", link: "https://getdp.co/Xyj" },
  { tribe: "Ijaw", link: "https://getdp.co/XyX" },
  { tribe: "kanuri", link: "https://getdp.co/Xyp" },
  { tribe: "Tiv", link: "https://getdp.co/XyL" },
  { tribe: "Nupe", link: "https://getdp.co/XCR" },
  { tribe: "Efik", link: "https://getdp.co/XD0" },
  { tribe: "Annang", link: "https://getdp.co/XDa" },
  { tribe: "Igala", link: "https://getdp.co/XDu" },
  { tribe: "Gwari", link: "https://getdp.co/XD1" },
  { tribe: "Jakun", link: "https://getdp.co/XDS" },
  { tribe: "Edo", link: "https://getdp.co/XDM" },
  { tribe: "Abua", link: "https://getdp.co/pkK" },
  { tribe: "Abayon", link: "https://getdp.co/pkd" },
  { tribe: "Achipa", link: "https://getdp.co/pkP" },
  { tribe: "Adim", link: "https://getdp.co/pki" },
  { tribe: "Adun", link: "https://getdp.co/pkV" },
  { tribe: "Affade", link: "https://getdp.co/pkj" },
  { tribe: "Afizere", link: "https://getdp.co/pko" },
  { tribe: "Afo", link: "https://getdp.co/pkX" },
  { tribe: "Agbo", link: "https://getdp.co/pkp" },
  { tribe: "Akaju-Ndem", link: "https://getdp.co/pkL" },
  { tribe: "Akweya-yachi", link: "https://getdp.co/pkN" },
  { tribe: "Alago", link: "https://getdp.co/pkr" },
  { tribe: "Amo", link: "https://getdp.co/pks" },
  { tribe: "Anaguta", link: "https://getdp.co/pkt" },
  { tribe: "Andoni", link: "https://getdp.co/pkv" },
  { tribe: "Angas", link: "https://getdp.co/pkw" },
  { tribe: "Ankwei", link: "https://getdp.co/pkE" },
  { tribe: "Anyima", link: "https://getdp.co/pkZ" },
  { tribe: "Attakar", link: "https://getdp.co/pkF" },
  { tribe: "Auyoka", link: "https://getdp.co/pky" },
  { tribe: "Awori", link: "https://getdp.co/pkz" },
  { tribe: "Ayu", link: "https://getdp.co/pkB" },
  { tribe: "Bachama", link: "https://getdp.co/p49" },
  { tribe: "Bachere", link: "https://getdp.co/p4b" },
  { tribe: "Bada", link: "https://getdp.co/p4T" },
  { tribe: "Bade", link: "https://getdp.co/p4c" },
  { tribe: "Bahumono", link: "https://getdp.co/p4U" },
  { tribe: "Bakulung", link: "https://getdp.co/p4f" },
  { tribe: "Bali", link: "https://getdp.co/p4W" },
  { tribe: "Bambora", link: "https://getdp.co/p4g" },
  { tribe: "Babur", link: "https://getdp.co/p4K" },
  { tribe: "baruba", link: "https://getdp.co/p4h" },
  { tribe: "Bamkubo", link: "https://getdp.co/p4P" },
  { tribe: "Banda", link: "https://getdp.co/p4i" },
  { tribe: "Banka", link: "https://getdp.co/p4V" },
  { tribe: "Banso", link: "https://getdp.co/p4j" },
  { tribe: "Bara", link: "https://getdp.co/p4o" },
  { tribe: "Barke", link: "https://getdp.co/p4X" },
  { tribe: "Bashiri", link: "https://getdp.co/p88" },
  { tribe: "Bassa", link: "https://getdp.co/p84" },
  { tribe: "Batta", link: "https://getdp.co/p8k" },
  { tribe: "Baushi", link: "https://getdp.co/p83" },
  { tribe: "Baya", link: "https://getdp.co/p8d" },
  { tribe: "Bekwarra", link: "https://getdp.co/p82" },
  { tribe: "Bele", link: "https://getdp.co/p8M" },
  { tribe: "Betso", link: "https://getdp.co/p8S" },
  { tribe: "Bette", link: "https://getdp.co/p81" },
  { tribe: "Bilei", link: "https://getdp.co/p8u" },
  { tribe: "Bille", link: "https://getdp.co/p8a" },
  { tribe: "Bina", link: "https://getdp.co/p80" },
  { tribe: "Bini (Edo)", link: "https://getdp.co/p4R" },
  { tribe: "Birom", link: "https://getdp.co/p4n" },
  { tribe: "Bkkos", link: "https://getdp.co/p4Q" },
  { tribe: "Bobua", link: "https://getdp.co/p4J" },
  { tribe: "Boki(Nki)", link: "https://getdp.co/p4I" },
  { tribe: "Boko", link: "https://getdp.co/p4H" },
  { tribe: "Bole(Bolewa)", link: "https://getdp.co/p4G" },
  { tribe: "Boma", link: "https://getdp.co/p4m" },
  { tribe: "Bomboro", link: "https://getdp.co/p4x" },
  { tribe: "Botlere", link: "https://getdp.co/p4D" },
  { tribe: "Buduma", link: "https://getdp.co/p8_" },
  { tribe: "Buji", link: "https://getdp.co/p4C" },
  { tribe: "Buli", link: "https://getdp.co/p4B" },
  { tribe: "Bunu", link: "https://getdp.co/p4z" },
  { tribe: "Bura", link: "https://getdp.co/p4y" },
  { tribe: "Burak", link: "https://getdp.co/p4F" },
  { tribe: "Burma", link: "https://getdp.co/p4Z" },
  { tribe: "Buru", link: "https://getdp.co/p4E" },
  { tribe: "Bwall", link: "https://getdp.co/p4A" },
  { tribe: "Bwatiye", link: "https://getdp.co/p45" },
  { tribe: "Bwazza", link: "https://getdp.co/p4s" },
  { tribe: "chama", link: "https://getdp.co/p_M" },
  { tribe: "chamba", link: "https://getdp.co/p_3" },
  { tribe: "chamo", link: "https://getdp.co/p_2" },
  { tribe: "chibok", link: "https://getdp.co/p_d" },
  { tribe: "chinine", link: "https://getdp.co/p_k" },
  { tribe: "chip", link: "https://getdp.co/p_4" },
  { tribe: "chokobo", link: "https://getdp.co/p_8" },
  { tribe: "chukkol", link: "https://getdp.co/p__" },
  { tribe: "daba", link: "https://getdp.co/p_l" },
  { tribe: "dadiya", link: "https://getdp.co/p_9" },
  { tribe: "daka", link: "https://getdp.co/p_b" },
  { tribe: "dakarkari", link: "https://getdp.co/p_T" },
  { tribe: "danda", link: "https://getdp.co/p_U" },
  { tribe: "dangsa", link: "https://getdp.co/p_e" },
  { tribe: "daza", link: "https://getdp.co/p_f" },
  { tribe: "degema", link: "https://getdp.co/p_W" },
  { tribe: "deno", link: "https://getdp.co/p_g" },
  { tribe: "Dghwede", link: "https://getdp.co/p_h" },
  { tribe: "diba", link: "https://getdp.co/p_K" },
  { tribe: "Deomak", link: "https://getdp.co/p_i" },
  { tribe: "duma", link: "https://getdp.co/p_P" },
  { tribe: "ebana", link: "https://getdp.co/p_o" },
  { tribe: "Ebirra", link: "https://getdp.co/p_X" },
  { tribe: "ebu", link: "https://getdp.co/p_p" },
  { tribe: "egede", link: "https://getdp.co/p_L" },
  { tribe: "eggon", link: "https://getdp.co/p_q" },
  { tribe: "egun", link: "https://getdp.co/p_N" },
  { tribe: "eket", link: "https://getdp.co/p_r" },
  { tribe: "esan", link: "https://getdp.co/p_s" },
  { tribe: "etche", link: "https://getdp.co/p_O" },
  { tribe: "etolu", link: "https://getdp.co/p_v" },
  { tribe: "etung", link: "https://getdp.co/p_t" },
  { tribe: "etuno", link: "https://getdp.co/p_5" },
  { tribe: "fyam", link: "https://getdp.co/p_A" },
  { tribe: "Ga'anda", link: "https://getdp.co/p_F" },
  { tribe: "gade", link: "https://getdp.co/p_y" },
  { tribe: "galambi", link: "https://getdp.co/p_B" },
  { tribe: "gamergu", link: "https://getdp.co/p_6" },
  { tribe: "gavako", link: "https://getdp.co/p_C" },
  { tribe: "gbedde", link: "https://getdp.co/p_D" },
  { tribe: "gengle", link: "https://getdp.co/p_x" },
  { tribe: "gera", link: "https://getdp.co/p_m" },
  { tribe: "geruma", link: "https://getdp.co/p_G" },
  { tribe: "ginkwak", link: "https://getdp.co/p_H" },
  { tribe: "gira", link: "https://getdp.co/p_I" },
  { tribe: "gizigz", link: "https://getdp.co/p_7" },
  { tribe: "goernai", link: "https://getdp.co/p_J" },
  { tribe: "gokana", link: "https://getdp.co/p_n" },
  { tribe: "gombi", link: "https://getdp.co/p_R" },
  { tribe: "gonia", link: "https://getdp.co/pl1" },
  { tribe: "gornun", link: "https://getdp.co/plu" },
  { tribe: "gubi", link: "https://getdp.co/plS" },
  { tribe: "gude", link: "https://getdp.co/plM" },
  { tribe: "gudu", link: "https://getdp.co/pl2" },
  { tribe: "gure", link: "https://getdp.co/pld" },
  { tribe: "gurmana", link: "https://getdp.co/pl3" },
  { tribe: "gururntum", link: "https://getdp.co/plk" },
  { tribe: "gusu", link: "https://getdp.co/pl4" },
  { tribe: "gwa(gurawa)", link: "https://getdp.co/pl8" },
  { tribe: "gwamba", link: "https://getdp.co/pl8" },
  { tribe: "gwandara", link: "https://getdp.co/pll" },
  { tribe: "gwom", link: "https://getdp.co/pl9" },
  { tribe: "gwoza", link: "https://getdp.co/plb" },
  { tribe: "gyem", link: "https://getdp.co/plb" },
  //   { tribe: "higi", link: "" },
  //   { tribe: "holma", link: "" },
  //   { tribe: "hona", link: "" },
  //   { tribe: "ibeno", link: "" },
  //   { tribe: "ichen", link: "" },
  //   { tribe: "idoma", link: "" },
  //   { tribe: "ijumu", link: "" },
  //   { tribe: "ikorn", link: "" },
  //   { tribe: "ilyala", link: "" },
  //   { tribe: "ilzonjo", link: "" },
  //   { tribe: "irigwe", link: "" },
  //   { tribe: "isoko", link: "" },
  //   { tribe: "itsekiri", link: "" },
  //   { tribe: "jaba", link: "" },
  //   { tribe: "jahuna", link: "" },
  //   { tribe: "jaku", link: "" },
  //   { tribe: "jara", link: "" },
  //   { tribe: "jere", link: "" },
  //   { tribe: "jero", link: "" },
  //   { tribe: "jibu", link: "" },
  //   { tribe: "jidda-abu", link: "" },
  //   { tribe: "jimbin", link: "" },
  //   { tribe: "jirai", link: "" },
  //   { tribe: "jonjo", link: "" },
  //   { tribe: "jukun", link: "" },
  //   { tribe: "kaba", link: "" },
  //   { tribe: "kadara", link: "" },
  //   { tribe: "kafanchan", link: "" },
  //   { tribe: "kaje", link: "" },
  //   { tribe: "kajuru", link: "" },
  //   { tribe: "kaka", link: "" },
  //   { tribe: "kamaku", link: "" },
  //   { tribe: "kambari", link: "" },
  //   { tribe: "kambu", link: "" },
  //   { tribe: "kamo", link: "" },
  //   { tribe: "kanakuru", link: "" },
  //   { tribe: "kanembu", link: "" },
  //   { tribe: "kanikon", link: "" },
  //   { tribe: "kantana", link: "" },
  //   { tribe: "ouguri", link: "" },
  //   { tribe: "palli", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "Qanawuri", link: "" },
  //   { tribe: "sikdi", link: "" },
  //   { tribe: "siri", link: "" },
  //   { tribe: "srubu", link: "" },
  //   { tribe: "sukur", link: "" },
  //   { tribe: "sura", link: "" },
  //   { tribe: "tangale", link: "" },
  //   { tribe: "tarok", link: "" },
  //   { tribe: "teme", link: "" },
  //   { tribe: "tera", link: "" },
  //   { tribe: "teshena", link: "" },
  //   { tribe: "tigon", link: "" },
  //   { tribe: "tikar", link: "" },
  //   { tribe: "tula", link: "" },
  //   { tribe: "tur", link: "" },
  //   { tribe: "ubbo", link: "" },
  //   { tribe: "ufia", link: "" },
  //   { tribe: "ukelle", link: "" },
  //   { tribe: "ukwani", link: "" },
  //   { tribe: "uncinda", link: "" },
  //   { tribe: "uneme", link: "" },
  //   { tribe: "ura", link: "" },
  //   { tribe: "urhobo", link: "" },
  //   { tribe: "utonkong", link: "" },
  //   { tribe: "uyanga", link: "" },
  //   { tribe: "vemgo", link: "" },
  //   { tribe: "verre", link: "" },
  //   { tribe: "wagga", link: "" },
  //   { tribe: "waja", link: "" },
  //   { tribe: "waka", link: "" },
  //   { tribe: "warja", link: "" },
  //   { tribe: "warji", link: "" },
  //   { tribe: "wula", link: "" },
  //   { tribe: "wurbo", link: "" },
  //   { tribe: "wurkun", link: "" },
  //   { tribe: "yache", link: "" },
  //   { tribe: "yagba", link: "" },
  //   { tribe: "yakurr", link: "" },
  //   { tribe: "yalla", link: "" },
  //   { tribe: "yandang", link: "" },
  //   { tribe: "yergan", link: "" },
  //   { tribe: "yott", link: "" },
  //   { tribe: "yumu", link: "" },
  //   { tribe: "yungur", link: "" },
  //   { tribe: "yuom", link: "" },
  //   { tribe: "zabara", link: "" },
  //   { tribe: "zaranda", link: "" },
  //   { tribe: "zarma", link: "" },
  //   { tribe: "zayam", link: "" },
  //   { tribe: "zul", link: "" },
];
