export const getDps = [
  { tribe: "Fulani", link: "https://getdp.co/Xyi" },
  { tribe: "Hausa", link: "https://getdp.co/XyV" },
  { tribe: "Yoruba", link: "https://getdp.co/Xyq" },
  { tribe: "Igbo", link: "https://getdp.co/Xyo" },
  { tribe: "Ibibio", link: "https://getdp.co/Xyj" },
  { tribe: "Ijaw", link: "https://getdp.co/XyX" },
  { tribe: "kanuri", link: "https://getdp.co/Xyp" },
  { tribe: "Tiv", link: "https://getdp.co/XyL" },
  { tribe: "Nupe", link: "https://getdp.co/XCR" },
  { tribe: "Efik", link: "https://getdp.co/XD0" },
  { tribe: "Annang", link: "https://getdp.co/XDa" },
  { tribe: "Igala", link: "https://getdp.co/XDu" },
  { tribe: "Gwari", link: "https://getdp.co/XD1" },
  { tribe: "Jakun", link: "https://getdp.co/XDS" },
  { tribe: "Edo", link: "https://getdp.co/XDM" },
  { tribe: "Abua", link: "https://getdp.co/pkK" },
  { tribe: "Abayon", link: "https://getdp.co/pkd" },
  { tribe: "Achipa", link: "https://getdp.co/pkP" },
  { tribe: "Adim", link: "https://getdp.co/pki" },
  { tribe: "Adun", link: "https://getdp.co/pkV" },
  { tribe: "Affade", link: "https://getdp.co/pkj" },
  { tribe: "Afizere", link: "https://getdp.co/pko" },
  { tribe: "Afo", link: "https://getdp.co/pkX" },
  { tribe: "Agbo", link: "https://getdp.co/pkp" },
  { tribe: "Akaju-Ndem", link: "https://getdp.co/pkL" },
  { tribe: "Akweya-yachi", link: "https://getdp.co/pkN" },
  { tribe: "Alago", link: "https://getdp.co/pkr" },
  { tribe: "Amo", link: "https://getdp.co/pks" },
  { tribe: "Anaguta", link: "https://getdp.co/pkt" },
  { tribe: "Andoni", link: "https://getdp.co/pkv" },
  { tribe: "Angas", link: "https://getdp.co/pkw" },
  { tribe: "Ankwei", link: "https://getdp.co/pkE" },
  { tribe: "Anyima", link: "https://getdp.co/pkZ" },
  { tribe: "Attakar", link: "https://getdp.co/pkF" },
  { tribe: "Auyoka", link: "https://getdp.co/pky" },
  { tribe: "Awori", link: "https://getdp.co/pkz" },
  { tribe: "Ayu", link: "https://getdp.co/pkB" },
  { tribe: "Bachama", link: "https://getdp.co/p49" },
  { tribe: "Bachere", link: "https://getdp.co/p4b" },
  { tribe: "Bada", link: "https://getdp.co/p4T" },
  { tribe: "Bade", link: "https://getdp.co/p4c" },
  { tribe: "Bahumono", link: "https://getdp.co/p4U" },
  { tribe: "Bakulung", link: "https://getdp.co/p4f" },
  { tribe: "Bali", link: "https://getdp.co/p4W" },
  { tribe: "Bambora", link: "https://getdp.co/p4g" },
  { tribe: "Babur", link: "https://getdp.co/p4K" },
  { tribe: "baruba", link: "https://getdp.co/p4h" },
  { tribe: "Bamkubo", link: "https://getdp.co/p4P" },
  { tribe: "Banda", link: "https://getdp.co/p4i" },
  { tribe: "Banka", link: "https://getdp.co/p4V" },
  { tribe: "Banso", link: "https://getdp.co/p4j" },
  { tribe: "Bara", link: "https://getdp.co/p4o" },
  { tribe: "Barke", link: "https://getdp.co/p4X" },
  { tribe: "Bashiri", link: "https://getdp.co/p88" },
  { tribe: "Bassa", link: "https://getdp.co/p84" },
  { tribe: "Batta", link: "https://getdp.co/p8k" },
  { tribe: "Baushi", link: "https://getdp.co/p83" },
  { tribe: "Baya", link: "https://getdp.co/p8d" },
  { tribe: "Bekwarra", link: "https://getdp.co/p82" },
  { tribe: "Bele", link: "https://getdp.co/p8M" },
  { tribe: "Betso", link: "https://getdp.co/p8S" },
  { tribe: "Bette", link: "https://getdp.co/p81" },
  { tribe: "Bilei", link: "https://getdp.co/p8u" },
  { tribe: "Bille", link: "https://getdp.co/p8a" },
  { tribe: "Bina", link: "https://getdp.co/p80" },
  { tribe: "Bini (Edo)", link: "https://getdp.co/p4R" },
  { tribe: "Birom", link: "https://getdp.co/p4n" },
  { tribe: "Bkkos", link: "https://getdp.co/p4Q" },
  { tribe: "Bobua", link: "https://getdp.co/p4J" },
  { tribe: "Boki(Nki)", link: "https://getdp.co/p4I" },
  { tribe: "Boko", link: "https://getdp.co/p4H" },
  { tribe: "Bole(Bolewa)", link: "https://getdp.co/p4G" },
  { tribe: "Boma", link: "https://getdp.co/p4m" },
  { tribe: "Bomboro", link: "https://getdp.co/p4x" },
  { tribe: "Botlere", link: "https://getdp.co/p4D" },
  { tribe: "Buduma", link: "https://getdp.co/p8_" },
  { tribe: "Buji", link: "https://getdp.co/p4C" },
  { tribe: "Buli", link: "https://getdp.co/p4B" },
  { tribe: "Bunu", link: "https://getdp.co/p4z" },
  { tribe: "Bura", link: "https://getdp.co/p4y" },
  { tribe: "Burak", link: "https://getdp.co/p4F" },
  { tribe: "Burma", link: "https://getdp.co/p4Z" },
  { tribe: "Buru", link: "https://getdp.co/p4E" },
  { tribe: "Bwall", link: "https://getdp.co/p4A" },
  { tribe: "Bwatiye", link: "https://getdp.co/p45" },
  { tribe: "Bwazza", link: "https://getdp.co/p4s" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
  //   { tribe: "", link: "" },
];
